title: Boryana Dyankova
description: Graphic design
email: bo.dyankova@gmail.com

baseurl: "/Portfolio"
url: ""
destination: "docs"
twitter_username: jekyllrb
github_username:  BoryanaD

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  # - _site
  # - scss - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
